[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'equalsraf/neovim-gui-shim'

# Lang settings
# c/c++
[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
let g:deplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deplete#sources#clang#clang_header = '/usr/include/clang-c'
'''

on_ft = ['c', 'c++', 'cmake']
depends = ['deplete.nvim']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
